# On repart de l'image de base choisie dans le compose
FROM apache/airflow:3.1.0

USER airflow

COPY requirements.txt .

# Installation de uv pour garder la cohérence avec votre service ETL
RUN pip install --no-cache-dir -r requirements.txt